channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.6
  - bioconda::bowtie2=2.3.4
  - bioconda::samtools=1.3.1
  - conda-forge::biopython=1.79
  - bioconda::pysam=0.19.1
  - bioconda::diamond=0.9.29
  - conda-forge::pandas=0.20
