bump_version: null
lint:
  actions_ci: false
  files_exist:
    - conf/modules.config
  files_unchanged:
    - .gitattributes
nf_core_version: 3.0.0
org_path: null
repository_type: pipeline
template:
  author: "@CarsonJM"
  description: Identification, annotation, and quantification of phages in (meta)-genomic
    sequences
  force: false
  is_nfcore: true
  name: phageannotator
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0dev
update: null
