repository_type: pipeline
lint:
  actions_ci: false
  files_exist:
    - conf/modules.config
    - .github/workflows/linting_comment.yml
  files_unchanged:
    - .gitattributes
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
